# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonExam_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
