# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonExam_app', '0002_auto_20170818_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='startdate',
        ),
    ]
