# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonExam_app', '0002_auto_20170818_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
