# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonExam_app', '0003_auto_20170818_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
